url: https://wrx4242.github.io
baseurl: /

host: 0.0.0.0

# Site settings
title: Стоковый WRX
email: zhukov.alex@gmail.com
description: "Subaru WRX 2015-го модельного года. Полный сток, не бит, не крашен, отвечаю пацаны!"


# Team names, titles and social links
people:
- name: Субару на подоле
  pic: 1
  position: Гарантийное СТО, остался доволен, ничего не сломали.
  link: http://subaru.kiev.ua

- name: Субару Хаус
  pic: 2
  position: Честные ребята, менял мелочи по подвеске, проходил ТО
  link: http://subaruhouse.com/

- name: Сам старался
  pic: 3
  position: Программист
  link: https://facebook.com/zhukov.alex

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
